# Generated by Django 5.0 on 2023-12-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0002_alter_category_solid_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='solid_out',
            new_name='sold_out',
        ),
    ]
