# Generated by Django 5.0 on 2023-12-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0003_rename_solid_out_category_sold_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_images', models.ImageField(upload_to='images/products')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmanager.category')),
            ],
        ),
    ]
