# Generated by Django 5.0 on 2023-12-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0005_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catgory_details',
            new_name='category_details',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_availabele',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sold_out',
        ),
        migrations.AddField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
