# Generated by Django 5.0 on 2024-01-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmanager', '0008_remove_productvariant_price_productram_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductRam',
        ),
        migrations.DeleteModel(
            name='ProductRom',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
